### ISSUE TITLE
Finalize Desktop Styling 

### ISSUE THREAD

**Issue by ShaneMPutnam** [Dewberry/fcast-dashboard#19]

**Comment by albrazeau** [comment]
Making either of the maps full screen messes with the apps styling and sizing. Resizing the window also does this. I think it has to do with the map css.

**Comment by Tmodurr** [comment]
> Making either of the maps full screen messes with the apps styling and sizing. Resizing the window also does this. I think it has to do with the map css.

You could set max-width on .areamap (wrapper element around .area-map.container).  Maybe a band aid solution...
