### ISSUE TITLE
stage anomalies from rating curve calculation

### ISSUE THREAD

**Issue by slawler** [Dewberry/fcast-dashboard#35]
Seeing these spikes again. Capturing here so that we can look back at this data and see what is causing this behavior.

![image](https://user-images.githubusercontent.com/12917287/141646301-037b32a3-3924-43e4-ba26-875f7e362110.png)

**Comment by mxkpp** [comment]
Resolved in https://github.com/Dewberry/fcast-dashboard/commit/ceb42bb14dc9c5e7d8c88422228162fc095bca9c via changes to main forecast function (Postgres server function).
